### ISSUE TITLE
Make a big BINGO button

### ISSUE THREAD

**Issue by gisellegk** [team178/bingo#11]
Bingo button Tasks:
- [x] Make the BINGO button HTML
- [x] Style it so that it’s hidden by default
- [x] Style state: all shiny when it’s like “CLICK ME CLICK ME”
- [x] Create a Javascript function that either shows or hides it.

**Comment by gisellegk** [comment]
I closed #10 but make sure that the show/hide behavior is attached to checkForWin :)

**Comment by TJScalzo** [comment]
It can probably do with being more shiny... Maybe add hover stuff using :before and :after to add a halo-like glow?

**Comment by gisellegk** [comment]
I love the shine animation thing it's got! and yes definitely make it glow when you hover.

Do you think it will stretch the header if we decided to add the custom button back in? Or we could make it wider and put it between the header and the board?

**Comment by TJScalzo** [comment]
I think we can leave the custom button out until it has that functionality. If we do add the feature though, I think we could move where the bingo button appears. It could be moved somewhere more obvious. (Like the free space? Or would that be too confusing...)

**Comment by gisellegk** [comment]
I think it would be better if we move the bingo button now but leave the custom button out until it does something.

I'd like to see what it would look like on top of the free space, it could go either way.
