### ISSUE TITLE
Bingo WIN behavior

### ISSUE THREAD

**Issue by gisellegk** [team178/bingo#12]
Bingo Splash screen:
You get to decide what happens when someone wins
Maybe confetti falls

- [x] Create Pop-up
- [x] Add Twitter share button
- [x] Add Facebook share button
- [x] Falling confetti would be cool

**Comment by gisellegk** [comment]
I'm thinking it should bring up a pop up that has social media buttons to share your win and a "play again?" button

it would be cool if you could share an image of your bingo board too but idk how to do that

**Comment by TJScalzo** [comment]
http://ngiriraj.com/pages/htmltable_export/demo.php
Helpful? idk

**Comment by TJScalzo** [comment]
This seems like it's pretty much done! I'm going to close it.

**Comment by gisellegk** [comment]
@TJScalzo oh yeah I was going to ask you if you liked the confetti on the title or the contents better, I think it might have been on a fb message but I meant to put it here. But that's a small detail and yeah the task is technically done

**Comment by TJScalzo** [comment]
I like it on the title. The effect's width works better with that than the content.
