### ISSUE TITLE
Create 5x5 "Board" element

### ISSUE THREAD

**Issue by gisellegk** [team178/bingo#2]
- [x] HTML: Create board that can be interacted with via CSS/JS
- [x] CSS: Default template

Helpful links:
https://css-tricks.com/accessible-simple-responsive-tables/
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by TJScalzo** [comment]
This link is likely what I'll model the responsive table after: http://codepen.io/dbushell/pen/wGaamR
I'm not exactly sure when I'll do this, but it'll be soon.

**Comment by TJScalzo** [comment]
I'm having trouble getting it to center on the page for some reason.
Another thing I'm using as a reference is this: http://threadbarecanvas.azurewebsites.net/jquery/bingo-card-javascript-and-jquery/

**Comment by gisellegk** [comment]
@TJScalzo can you push your code so we can see what you have? Or screenshots/describe what's up

**Comment by TJScalzo** [comment]
@gisellegk sure, I'll push it when I get home.

**Comment by TJScalzo** [comment]
Ok, I just remembered this, @gisellegk. 

I'm not sure why, but it's stubbornly refusing to center itself. I wonder if I'm going about this the wrong way and should just use divs?

**Comment by TJScalzo** [comment]
Also, on the topic of locally running this:
I added `/bingo` to the .gitignore of the main site. Then, I cloned this repo into the team178.github.io repo on my computer. This allowed Jekyll to render it when run inside of team178.github.io. I just needed to manage git inside of /bingo.
