### ISSUE TITLE
Create pop-up for instructions

### ISSUE THREAD

**Issue by gisellegk** [team178/bingo#8]
Welcome to FRC Kickoff Bingo! Fill out a card and get excited for FIRST STEAMWORKS! Whenever something said or done matches your bingo card, click on the box to check it off. If you get 5 in a row in any direction - vertical, horizontal, or diagonal, click the BINGO button to win!

**Comment by TJScalzo** [comment]
https://limonte.github.io/sweetalert2/

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
